approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

#npmRegistryServer: "https://nexus.ops.engage.int.ringcentral.com/repository/npm-proxy/"
#npmRegistryServer: "https://nexus3.int.rclabenv.com/repository/npmjs/"
#npmRegistryServer: 'https://nexus3.int.rclabenv.com/repository/npm-all/'
