#!/usr/bin/env node

/**
 * @kirill.konshin/lint
 *
 * This script symlinks all markdown rule files from the package into the consuming
 * project's `.claude/rules` (auto-discovered by Claude Code) and `.codex/rules` directories,
 * symlinks every package skill into `.claude/skills/<name>/` and `.codex/skills/<name>/`
 * (SKILL.md plus the package README.md alongside it, so a skill can reference `@README.md`),
 * and generates an `AGENTS.md` file for other tools, with `CLAUDE.md` symlinked to `AGENTS.md`.
 *
 * Usage:
 *   lint-prepare init    - Initialize AGENTS.md in the current directory (default)
 *   lint-prepare update  - Force update AGENTS.md even if it exists
 *   lint-prepare         - Same as init
 *
 * The module also exports its functions and only runs `main()` when executed directly,
 * so it can be imported (for testing/reuse) without side effects.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

type Rule = { file: string; name: string; description?: string; content: string };
type Skill = { file: string; name: string };
type ExistingFile = { exists: boolean; generated: boolean; customSection: string | null };

const AGENTS_FILE = 'AGENTS.md';
const CLAUDE_FILE = 'CLAUDE.md';
const RULES_DIR = path.join(__dirname, '../rules');
const SKILLS_DIR = path.join(__dirname, '../skills');
const README_FILE = path.join(__dirname, '../README.md');
const RULES_TARGET_DIRS = ['.claude/rules', '.codex/rules'];
const SKILLS_TARGET_DIRS = ['.claude/skills', '.codex/skills'];
// Codex keeps its own command policies in `.codex/rules/*.rules` (https://developers.openai.com/codex/rules)
const CODEX_POLICY_EXT = '.rules';
const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;
const HEADER = `# AI Agent Rules

This file is auto-generated by @kirill.konshin/lint. Do not edit directly - customize by adding your own rules below the generated section.

---`;

const FOOTER = `---

# Custom Rules

Add your project-specific rules below the comment line.`;

const GENERATED_MARKER = '<!-- @kirill.konshin/lint:generated -->';

/**
 * Relative path between the REAL locations of `from` and `to`: the cwd and the package (workspaces, yalc, pnpm store)
 * may be reached through symlinks, and a path computed between a symlinked and a real location dangles.
 */
const realRelative = (from: string, to: string): string => path.relative(fs.realpathSync(from), fs.realpathSync(to));

/**
 * `monorepo-turbo-nx` -> `Monorepo turbo nx`
 */
const toTitle = (name: string): string => {
    const title = name.replaceAll('-', ' ');
    return title.charAt(0).toUpperCase() + title.slice(1);
};

/**
 * The `description` field of a rule's YAML frontmatter.
 */
const readDescription = (content: string): string | undefined => {
    const frontmatter = FRONTMATTER.exec(content)?.[1];
    const description: unknown = frontmatter ? parse(frontmatter)?.description : undefined;
    return typeof description === 'string' ? description.trim() : undefined;
};

/**
 * Read all markdown files from the package rules directory.
 */
export function readRules(): Rule[] {
    const rules: Rule[] = [];

    if (!fs.existsSync(RULES_DIR)) {
        console.error(`Rules directory not found: ${RULES_DIR}`);
        process.exit(1);
    }

    const files = fs
        .readdirSync(RULES_DIR)
        .filter((f) => f.endsWith('.md'))
        .sort();

    for (const file of files) {
        const filePath = path.join(RULES_DIR, file);
        const content = fs.readFileSync(filePath, 'utf-8');
        rules.push({
            file,
            name: file.replace('.md', ''),
            description: readDescription(content),
            content,
        });
    }

    return rules;
}

/**
 * Read all markdown files from the package skills directory. Each file becomes its own skill, named after the file
 * (without extension) - e.g. `lint-repo.md` becomes the `lint-repo` skill.
 */
export function readSkills(): Skill[] {
    if (!fs.existsSync(SKILLS_DIR)) return [];

    return fs
        .readdirSync(SKILLS_DIR)
        .filter((f) => f.endsWith('.md'))
        .sort()
        .map((file) => ({ file, name: file.replace('.md', '') }));
}

/**
 * Fail if `.claude/rules` or `.codex/rules` contains anything that isn't a symlink - we don't want to
 * silently blow away a real file/directory a user placed there by hand. Codex command policies
 * (`*.rules`) are not ours and are left alone.
 */
export function checkRulesDirSafety(rulesTargetDir: string): void {
    if (!fs.existsSync(rulesTargetDir)) return;

    for (const entry of fs.readdirSync(rulesTargetDir)) {
        const entryPath = path.join(rulesTargetDir, entry);

        if (!entry.endsWith(CODEX_POLICY_EXT) && !fs.lstatSync(entryPath).isSymbolicLink()) {
            console.error(`${entryPath} exists and is not a symlink.`);
            console.error('Remove or back it up manually, then re-run.');
            process.exit(1);
        }
    }
}

/**
 * Fail if `CLAUDE.md` exists and isn't a symlink - same reasoning as checkRulesDirSafety.
 */
export function checkClaudeMdSafety(claudeMdPath: string): void {
    let stat;

    try {
        stat = fs.lstatSync(claudeMdPath);
    } catch {
        return;
    }

    if (!stat.isSymbolicLink()) {
        console.error(`${CLAUDE_FILE} exists and is not a symlink.`);
        console.error('Remove or back it up manually, then re-run.');
        process.exit(1);
    }
}

/**
 * Symlink rules into the consuming project's `.claude/rules` and `.codex/rules` directories.
 * Safe to clear and recreate: checkRulesDirSafety already guaranteed every existing
 * entry except Codex command policies (kept) is a symlink.
 *
 * FIXME Codex Includes
 *   https://github.com/openai/codex/issues/17401
 *   https://github.com/openai/codex/issues/6038
 *   32kb limit https://github.com/openai/codex/issues/13386
 *
 * TODO: generate `.claude/CLAUDE.md` with an index of the symlinked rules, for humans browsing `.claude/rules` manually
 *   (Claude Code itself doesn't need it - it auto-loads every file under `.claude/rules` regardless of whether it's
 *   indexed anywhere).
 */
export function symlinkRules(cwd: string, rules: Rule[]): string[] {
    return RULES_TARGET_DIRS.map((dir) => {
        const targetDir = path.join(cwd, dir);

        fs.mkdirSync(targetDir, { recursive: true });

        for (const entry of fs.readdirSync(targetDir)) {
            if (!entry.endsWith(CODEX_POLICY_EXT)) fs.unlinkSync(path.join(targetDir, entry));
        }

        for (const rule of rules) {
            const source = path.join(RULES_DIR, rule.file);
            const linkPath = path.join(targetDir, rule.file);
            fs.symlinkSync(realRelative(targetDir, source), linkPath);
        }

        return targetDir;
    });
}

/**
 * Fail if a skill's target directory (e.g. `.claude/skills/lint-repo`) contains anything
 * that isn't a symlink - same reasoning as checkRulesDirSafety. Only the specific skill's
 * own subdirectory is checked/wiped, not the whole `.claude/skills` or `.codex/skills`
 * parent, since other packages (or the user) may keep unrelated skills there.
 */
export function checkSkillDirSafety(skillDir: string): void {
    if (!fs.existsSync(skillDir)) return;

    for (const entry of fs.readdirSync(skillDir)) {
        const entryPath = path.join(skillDir, entry);

        if (!fs.lstatSync(entryPath).isSymbolicLink()) {
            console.error(`${skillDir}/${entry} exists and is not a symlink.`);
            console.error('Remove or back it up manually, then re-run.');
            process.exit(1);
        }
    }
}

/**
 * Symlink each package skill into `<cwd>/.claude/skills/<name>/` and
 * `<cwd>/.codex/skills/<name>/`, so both Claude Code and Codex CLI can discover and run
 * them. The package README.md is symlinked alongside SKILL.md so a skill can reference it
 * via `@README.md` regardless of how the tool resolves relative mentions.
 */
export function symlinkSkills(cwd: string, skills: Skill[]): string[] {
    const targetDirs: string[] = [];
    const hasReadme = fs.existsSync(README_FILE);

    for (const skill of skills) {
        for (const targetRoot of SKILLS_TARGET_DIRS) {
            const skillDir = path.join(cwd, targetRoot, skill.name);

            checkSkillDirSafety(skillDir);

            fs.rmSync(skillDir, { recursive: true, force: true });
            fs.mkdirSync(skillDir, { recursive: true });

            const source = path.join(SKILLS_DIR, skill.file);
            const linkPath = path.join(skillDir, 'SKILL.md');
            fs.symlinkSync(realRelative(skillDir, source), linkPath);

            if (hasReadme) {
                const readmeLink = path.join(skillDir, 'README.md');
                fs.symlinkSync(realRelative(skillDir, README_FILE), readmeLink);
            }

            targetDirs.push(skillDir);
        }
    }

    return targetDirs;
}

/**
 * Symlink CLAUDE.md -> AGENTS.md so both point at the same generated content.
 */
export function symlinkClaudeMd(cwd: string): void {
    const claudeMdPath = path.join(cwd, CLAUDE_FILE);

    fs.rmSync(claudeMdPath, { force: true });
    fs.symlinkSync(AGENTS_FILE, claudeMdPath);
}

/**
 * Generate AGENTS.md with a `# Rules` section: a `## Title` block per rule file with its
 * frontmatter `description` and a reference to the file.
 *
 * `.claude/rules/*.md` are symlinked by symlinkRules() above and auto-discovered by
 * Claude Code at launch (confirmed: Claude Code recursively loads every `.md` file
 * under `.claude/rules`, symlinks included) - no reference to them is needed here.
 * The sections below are for other tools that only read AGENTS.md.
 */
export function generateAgentsFile(rules: Rule[], cwd: string, customSection: string | null): string {
    // where the rules really are, e.g. `node_modules/@kirill.konshin/lint/rules`, `packages/lint/rules` in a workspace
    const relativeRulesDir = realRelative(cwd, RULES_DIR).split(path.sep).join('/');

    /**
     * @see https://code.claude.com/docs/en/memory#import-additional-files
     * @see https://github.com/anthropics/claude-code/issues/13614 @import -> @path/file.md in Claude
     * @see https://github.com/openai/codex/issues/17401 - no @path/file.md in Codex yet
     */
    const sections = rules.map((rule) => {
        const rulePath = `${relativeRulesDir}/${rule.file}`;

        return [
            `## ${toTitle(rule.name)}`,
            rule.description,
            `See instructions in @${rulePath} [${rulePath}](${rulePath}).`,
        ]
            .filter(Boolean)
            .join('\n\n');
    });

    const generated = `${HEADER}\n\n# Rules\n\n${sections.join('\n\n')}\n\n${FOOTER}\n\n${GENERATED_MARKER}`;

    return customSection ? `${generated}\n\n${customSection}\n` : `${generated}\n`;
}

/**
 * Check if AGENTS.md exists and was generated by this tool. When it was, also return
 * whatever follows the marker (the user's custom section) so it can be carried forward -
 * generateAgentsFile() always rebuilds the part above the marker from scratch, but must
 * never touch what a user wrote below it.
 */
export function checkExisting(targetPath: string): ExistingFile {
    if (!fs.existsSync(targetPath)) {
        return { exists: false, generated: false, customSection: null };
    }

    const content = fs.readFileSync(targetPath, 'utf-8');
    const markerIndex = content.indexOf(GENERATED_MARKER);
    const generated = markerIndex !== -1;
    const customSection = generated ? content.slice(markerIndex + GENERATED_MARKER.length).trim() : null;

    return { exists: true, generated, customSection };
}

/**
 * Main function
 */
export function main(): void {
    const args = process.argv.slice(2);
    const command = args[0] || 'init';
    const cwd = process.env.INIT_CWD || process.cwd();
    const targetPath = path.join(cwd, AGENTS_FILE);
    const claudeMdPath = path.join(cwd, CLAUDE_FILE);

    console.log(`@kirill.konshin/lint: ${command}`);
    console.log(`Target: ${targetPath}`);

    const { exists, generated, customSection } = checkExisting(targetPath);

    if (command === 'init') {
        if (exists && !generated) {
            console.log(`${AGENTS_FILE} exists and was not generated by this tool. Skipping.`);
            console.log('Use "lint-prepare update" to force overwrite, then merge manually.');
            return;
        }

        if (exists && generated) {
            console.log(`${AGENTS_FILE} exists and was generated by this tool. Updating...`);
        }
    }

    if (command === 'update' || command === 'init') {
        for (const dir of RULES_TARGET_DIRS) {
            checkRulesDirSafety(path.join(cwd, dir));
        }
        checkClaudeMdSafety(claudeMdPath);

        const rules = readRules();
        console.log(`Found ${rules.length} rule files: ${rules.map((r) => r.name).join(', ')}`);

        const targetRulesDirs = symlinkRules(cwd, rules);
        for (const targetRulesDir of targetRulesDirs) {
            console.log(`Symlinked rules to ${targetRulesDir}`);
        }

        const skills = readSkills();
        console.log(`Found ${skills.length} skill(s): ${skills.map((s) => s.name).join(', ')}`);

        const targetSkillDirs = symlinkSkills(cwd, skills);
        for (const targetSkillDir of targetSkillDirs) {
            console.log(`Symlinked skill to ${targetSkillDir}`);
        }

        const content = generateAgentsFile(rules, cwd, customSection);
        fs.writeFileSync(targetPath, content, 'utf-8');
        console.log(`${exists ? 'Updated' : 'Created'} ${AGENTS_FILE}`);

        symlinkClaudeMd(cwd);
        console.log(`Symlinked ${CLAUDE_FILE} -> ${AGENTS_FILE}`);
        return;
    }

    console.log(`Unknown command: ${command}`);
    console.log('Usage: lint-prepare [init|update]');
    process.exit(1);
}

// Only run when executed directly (e.g. `lint-prepare init`), not when imported.
if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(__filename)) {
    main();
}
