#!/usr/bin/env node

/**
 * @kirill.konshin/lint
 *
 * This script makes `rules`, `commands` and `skills` real directories in the consuming project's
 * `.agents` (canonical, cross-tool) and `.claude` (Claude Code), and fills them with
 * file symlinks only: package rules, commands and skills (every file a skill folder ships, plus the package
 * README.md next to its SKILL.md, so a skill can reference `@README.md`) go into both, pointing
 * straight at the installed package; the user's own files in `.agents` are mirrored into `.claude`. It also
 * generates an `AGENTS.md` file for other tools, with `CLAUDE.md` symlinked to `AGENTS.md`.
 *
 * Usage:
 *   lint-prepare init    - Initialize AGENTS.md in the current directory (default)
 *   lint-prepare update  - Force update AGENTS.md even if it exists
 *   lint-prepare         - Same as init
 *
 * The module also exports its functions and only runs `main()` when executed directly,
 * so it can be imported (for testing/reuse) without side effects.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * A rule file. `paths` scopes it: Claude Code loads it only for matching files.
 */
type Rule = { file: string; name: string; description?: string; paths?: string[]; content: string };
type Skill = { name: string };
type ExistingFile = { exists: boolean; generated: boolean; customSection: string | null };

const AGENTS_FILE = 'AGENTS.md';
const CLAUDE_FILE = 'CLAUDE.md';
const RULES_DIR = path.join(__dirname, '../rules');
const SKILLS_DIR = path.join(__dirname, '../skills');
const COMMANDS_DIR = path.join(__dirname, '../commands');
const README_FILE = path.join(__dirname, '../README.md');
// `.agents` is the cross-tool location (Codex, Cursor, Antigravity) holding the package links and the user's own
// files, the latter are mirrored into `.claude` (Claude Code reads nothing else)
const CANONICAL_AGENT_DIR = '.agents';
const MIRROR_AGENT_DIRS = ['.claude'];
const AGENT_DIRS = [CANONICAL_AGENT_DIR, ...MIRROR_AGENT_DIRS];
const AGENT_KINDS = ['rules', 'commands', 'skills'];
const GITIGNORE = '.gitignore';
const GITIGNORE_HEADER = '# Generated by @kirill.konshin/lint: symlinks it manages here, your own files stay tracked';
const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/;
const HEADER = `# AI Agent Rules

This file is auto-generated by @kirill.konshin/lint. Do not edit directly - customize by adding your own rules below the generated section.

---`;

const FOOTER = `---

# Custom Rules

Add your project-specific rules below the comment line.`;

const GENERATED_MARKER = '<!-- @kirill.konshin/lint:generated -->';

const lstat = (file: string): fs.Stats | undefined => fs.lstatSync(file, { throwIfNoEntry: false });

/**
 * `monorepo-turbo-nx` -> `Monorepo turbo nx`
 */
const toTitle = (name: string): string => {
    const title = name.replaceAll('-', ' ');
    return title.charAt(0).toUpperCase() + title.slice(1);
};

/**
 * A rule's YAML frontmatter, empty when it has none.
 */
const readFrontmatter = (content: string): Record<string, unknown> => {
    const frontmatter = FRONTMATTER.exec(content)?.[1];
    const parsed: unknown = frontmatter ? parse(frontmatter) : undefined;
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {};
};

/**
 * A frontmatter field read as a list of strings: one string, or a list of them.
 */
const stringList = (value: unknown): string[] | undefined => {
    const items = typeof value === 'string' ? [value] : Array.isArray(value) ? value : [];
    const strings = items.filter((item): item is string => typeof item === 'string' && item.trim() !== '');
    return strings.length ? strings : undefined;
};

/**
 * `file` is the path inside a rules dir, e.g. `auth.md` or `frontend/react.md`.
 */
const toRule = (file: string, content: string): Rule => {
    const { description, paths } = readFrontmatter(content);

    return {
        file,
        name: path.posix.basename(file, '.md'),
        description: typeof description === 'string' ? description.trim() : undefined,
        paths: stringList(paths),
        content,
    };
};

/**
 * Real files under `dir`, as paths relative to `root` - symlinks (incl. the package links next to them), linked
 * directories and dotfiles (`.gitignore`, `.DS_Store`) are skipped.
 */
function listRealFiles(root: string, dir = root): string[] {
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const entryPath = path.join(dir, entry.name);

        if (entry.name.startsWith('.')) return [];
        if (entry.isDirectory()) return listRealFiles(root, entryPath);
        return entry.isFile() ? [path.relative(root, entryPath)] : [];
    });
}

/**
 * Dead symlinks under `dir`, walking real directories only.
 */
function findDeadLinks(dir: string): string[] {
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const entryPath = path.join(dir, entry.name);

        if (entry.isDirectory()) return findDeadLinks(entryPath);
        return entry.isSymbolicLink() && !fs.existsSync(entryPath) ? [entryPath] : [];
    });
}

/**
 * Remove `link` and the directories it leaves empty, up to `root`.
 */
function removeLink(link: string, root: string): void {
    fs.unlinkSync(link);

    for (let dir = path.dirname(link); dir !== root && !fs.readdirSync(dir).length; dir = path.dirname(dir)) {
        fs.rmdirSync(dir);
    }
}

/**
 * mkdir -p `dir` (relative to cwd, starting with an agent dir, which itself may be a link) without going through
 * links below it: false when a part is a symlink or a file - those are the user's, nothing is written through them.
 */
function ensureRealDir(cwd: string, dir: string): boolean {
    const [agentDir, ...parts] = dir.split(path.sep);
    let current = path.join(cwd, agentDir);

    fs.mkdirSync(current, { recursive: true });

    for (const part of parts) {
        current = path.join(current, part);
        const stat = lstat(current);

        if (!stat) fs.mkdirSync(current);
        else if (!stat.isDirectory()) return false;
    }

    return true;
}

/**
 * Point `link` (relative to cwd) at `target`, unless the spot is the user's: a real file there, or a linked
 * directory on the way. Returns whether the link is in place.
 */
function placeLink(cwd: string, link: string, target: string): boolean {
    const linkPath = path.join(cwd, link);

    if (!ensureRealDir(cwd, path.dirname(link))) {
        console.log(`Skipped ${link}: ${path.dirname(link)} is not a real directory`);
        return false;
    }

    const stat = lstat(linkPath);

    if (stat && !stat.isSymbolicLink()) {
        console.log(`Kept ${link}: not a symlink`);
        return false;
    }

    // relative between REAL locations: cwd and the package (workspaces, yalc, pnpm store) may be reached through
    // symlinks, and a path computed between a symlinked and a real location dangles
    const text = path.relative(fs.realpathSync(path.dirname(linkPath)), target);

    if (stat && fs.readlinkSync(linkPath) === text) return true;
    if (stat) fs.unlinkSync(linkPath);
    fs.symlinkSync(text, linkPath);

    return true;
}

/**
 * Links listed in a `.gitignore` this tool generated - it doubles as the record of what to clean up next time.
 */
function readManifest(gitignore: string): string[] {
    const content = fs.existsSync(gitignore) ? fs.readFileSync(gitignore, 'utf-8') : '';

    if (!content.startsWith(GITIGNORE_HEADER)) return [];

    return content
        .split('\n')
        .filter((line) => line.startsWith('/') && line !== `/${GITIGNORE}`)
        .map((line) => path.normalize(line.slice(1)));
}

/**
 * Write the `.gitignore` listing `links` (remove it when there are none), unless the user owns that file.
 */
function writeManifest(gitignore: string, links: string[]): void {
    const exists = fs.existsSync(gitignore);

    if (exists && !fs.readFileSync(gitignore, 'utf-8').startsWith(GITIGNORE_HEADER)) return;

    if (!links.length) {
        if (exists) fs.unlinkSync(gitignore);
        return;
    }

    const entries = links.map((link) => `/${link.split(path.sep).join('/')}`).sort();
    fs.writeFileSync(gitignore, [GITIGNORE_HEADER, `/${GITIGNORE}`, ...entries, ''].join('\n'));
}

/**
 * Links to place, keyed by their path relative to cwd: package files into every agent dir, the user's own `.agents`
 * files into the mirrors. A user file wins over the package file at the same path.
 */
function plannedLinks(
    cwd: string,
    packageFiles: Map<string, string>,
    userFiles: Map<string, string>,
): Map<string, string> {
    const canonicalDir = path.join(fs.realpathSync(cwd), CANONICAL_AGENT_DIR);
    const links = new Map<string, string>();

    for (const [file, source] of packageFiles) {
        if (userFiles.has(file)) {
            console.log(`${path.join(CANONICAL_AGENT_DIR, file)} overrides the package file`);
            continue;
        }

        for (const dir of AGENT_DIRS) links.set(path.join(dir, file), fs.realpathSync(source));
    }

    for (const file of userFiles.keys()) {
        for (const dir of MIRROR_AGENT_DIRS) links.set(path.join(dir, file), path.join(canonicalDir, file));
    }

    return links;
}

/**
 * Read all markdown files from the package rules directory.
 */
export function readRules(): Rule[] {
    const rules: Rule[] = [];

    if (!fs.existsSync(RULES_DIR)) {
        console.error(`Rules directory not found: ${RULES_DIR}`);
        process.exit(1);
    }

    const files = fs
        .readdirSync(RULES_DIR)
        .filter((f) => f.endsWith('.md'))
        .sort();

    for (const file of files) {
        const filePath = path.join(RULES_DIR, file);
        rules.push(toRule(file, fs.readFileSync(filePath, 'utf-8')));
    }

    return rules;
}

/**
 * Read the package skills directory: every directory holding a `SKILL.md` is a skill named after the directory,
 * shipped with all its files (scripts, references, ...).
 */
export function readSkills(): Skill[] {
    if (!fs.existsSync(SKILLS_DIR)) return [];

    return fs
        .readdirSync(SKILLS_DIR, { withFileTypes: true })
        .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(SKILLS_DIR, entry.name, 'SKILL.md')))
        .map((entry) => ({ name: entry.name }))
        .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Read the package commands directory: every markdown file is a command named after the file.
 */
export function readCommands(): string[] {
    if (!fs.existsSync(COMMANDS_DIR)) return [];

    return fs
        .readdirSync(COMMANDS_DIR)
        .filter((f) => f.endsWith('.md'))
        .sort();
}

/**
 * Package files to link, keyed by their path inside an agent dir: `rules/<file>`, `commands/<file>`, and every file
 * of a skill at its own relative path, plus the package README.md next to its `SKILL.md` (unless the skill ships
 * one), so a skill can reference `@README.md`.
 */
export function packageFiles(rules: Rule[], skills: Skill[], commands: string[] = []): Map<string, string> {
    const files = new Map<string, string>();
    const hasReadme = fs.existsSync(README_FILE);

    for (const rule of rules) {
        files.set(path.join('rules', rule.file), path.join(RULES_DIR, rule.file));
    }

    for (const command of commands) {
        files.set(path.join('commands', command), path.join(COMMANDS_DIR, command));
    }

    for (const skill of skills) {
        const root = path.join(SKILLS_DIR, skill.name);
        const readme = path.join('skills', skill.name, 'README.md');

        for (const file of listRealFiles(root)) {
            files.set(path.join('skills', skill.name, file), path.join(root, file));
        }

        if (hasReadme && !files.has(readme)) files.set(readme, README_FILE);
    }

    return files;
}

/**
 * The user's own files in `.agents` `rules`, `commands` and `skills`, keyed like packageFiles() - everything there
 * except the package links (and dotfiles).
 */
export function readUserFiles(cwd: string): Map<string, string> {
    const files = new Map<string, string>();

    for (const kind of AGENT_KINDS) {
        const root = path.join(cwd, CANONICAL_AGENT_DIR, kind);

        if (!fs.statSync(root, { throwIfNoEntry: false })?.isDirectory()) continue;

        for (const file of listRealFiles(root)) {
            files.set(path.join(kind, file), path.join(root, file));
        }
    }

    return files;
}

/**
 * Make `rules`, `commands` and `skills` real directories in every agent dir and link the files we know into them:
 * package files into both, pointing straight at the package, and the user's own `.agents` files into `.claude`.
 * Real files and linked directories are the user's - never written over or through. Dead links are
 * removed, and so are links from the previous run that are no longer placed: each directory's generated `.gitignore`
 * records them (and keeps them out of git, so the user's own files there stay tracked).
 *
 * FIXME Codex Includes
 *   https://github.com/openai/codex/issues/17401
 *   https://github.com/openai/codex/issues/6038
 *   32kb limit https://github.com/openai/codex/issues/13386
 *
 * TODO: generate `.claude/CLAUDE.md` with an index of the symlinked rules, for humans browsing `.claude/rules` manually
 *   (Claude Code itself doesn't need it - it auto-loads every file under `.claude/rules` regardless of whether it's
 *   indexed anywhere).
 */
export function syncAgentDirs(cwd: string, packageFiles: Map<string, string>, userFiles: Map<string, string>): void {
    const links = plannedLinks(cwd, packageFiles, userFiles);

    for (const dir of AGENT_DIRS) {
        for (const kind of AGENT_KINDS) {
            const root = path.join(dir, kind);
            const rootPath = path.join(cwd, root);
            const gitignore = path.join(rootPath, GITIGNORE);

            if (!ensureRealDir(cwd, root)) {
                console.log(`Skipped ${root}: not a real directory`);
                continue;
            }

            for (const link of findDeadLinks(rootPath)) {
                removeLink(link, rootPath);
            }

            const placed: string[] = [];

            for (const [link, target] of links) {
                if (link.startsWith(root + path.sep) && placeLink(cwd, link, target)) {
                    placed.push(path.relative(root, link));
                }
            }

            for (const link of readManifest(gitignore)) {
                const linkPath = path.join(rootPath, link);
                if (!placed.includes(link) && lstat(linkPath)?.isSymbolicLink()) removeLink(linkPath, rootPath);
            }

            writeManifest(gitignore, placed);
        }
    }
}

/**
 * Rules as they end up in `.agents/rules`: the package ones plus the user's own, which win on the same file.
 */
export function installedRules(rules: Rule[], userFiles: Map<string, string>): Rule[] {
    const byFile = new Map(rules.map((rule) => [rule.file, rule]));
    const rulesDir = `rules${path.sep}`;

    for (const [file, source] of userFiles) {
        if (!file.startsWith(rulesDir) || !file.endsWith('.md')) continue;

        const ruleFile = file.slice(rulesDir.length).split(path.sep).join('/');
        byFile.set(ruleFile, toRule(ruleFile, fs.readFileSync(source, 'utf-8')));
    }

    return [...byFile].sort(([a], [b]) => (a < b ? -1 : 1)).map(([, rule]) => rule);
}

/**
 * Fail if `CLAUDE.md` exists and isn't a symlink - we don't want to silently blow away a file the user wrote.
 */
export function checkClaudeMdSafety(claudeMdPath: string): void {
    let stat;

    try {
        stat = fs.lstatSync(claudeMdPath);
    } catch {
        return;
    }

    if (!stat.isSymbolicLink()) {
        console.error(`${CLAUDE_FILE} exists and is not a symlink.`);
        console.error('Remove or back it up manually, then re-run.');
        process.exit(1);
    }
}

/**
 * Symlink CLAUDE.md -> AGENTS.md so both point at the same generated content.
 */
export function symlinkClaudeMd(cwd: string): void {
    const claudeMdPath = path.join(cwd, CLAUDE_FILE);

    fs.rmSync(claudeMdPath, { force: true });
    fs.symlinkSync(AGENTS_FILE, claudeMdPath);
}

/**
 * Generate AGENTS.md with a `# Rules` section: one entry per rule (the package's and the user's own) with
 * its frontmatter `description`, the `paths` it is scoped to and a plain link to its `.agents/rules` entry.
 *
 * The links are plain, never `@path` imports: Claude Code loads `.claude/rules` itself (syncAgentDirs() links them
 * there) and honours each rule's `paths`, while an `@` import would load every rule into every session, scoped or not.
 * Codex, which expands no `@`, reads this index.
 */
export function generateAgentsFile(rules: Rule[], customSection: string | null): string {
    const entries = rules.map((rule) => {
        // the canonical entry (a package link or the user's own file), not the package install path
        const rulePath = `${CANONICAL_AGENT_DIR}/rules/${rule.file}`;
        const description = rule.description ? ` — ${rule.description}` : '';
        const scope = rule.paths ? `; when touching ${rule.paths.map((glob) => `\`${glob}\``).join(', ')}` : '';

        return `- **${toTitle(rule.name)}**${description}${scope}: [${rulePath}](${rulePath})`;
    });

    const generated = `${HEADER}\n\n# Rules\n\n${entries.join('\n')}\n\n${FOOTER}\n\n${GENERATED_MARKER}`;

    return customSection ? `${generated}\n\n${customSection}\n` : `${generated}\n`;
}

/**
 * Check if AGENTS.md exists and was generated by this tool. When it was, also return
 * whatever follows the marker (the user's custom section) so it can be carried forward -
 * generateAgentsFile() always rebuilds the part above the marker from scratch, but must
 * never touch what a user wrote below it.
 */
export function checkExisting(targetPath: string): ExistingFile {
    if (!fs.existsSync(targetPath)) {
        return { exists: false, generated: false, customSection: null };
    }

    const content = fs.readFileSync(targetPath, 'utf-8');
    const markerIndex = content.indexOf(GENERATED_MARKER);
    const generated = markerIndex !== -1;
    const customSection = generated ? content.slice(markerIndex + GENERATED_MARKER.length).trim() : null;

    return { exists: true, generated, customSection };
}

/**
 * Main function
 */
export function main(): void {
    const args = process.argv.slice(2);
    const command = args[0] || 'init';
    const cwd = process.env.INIT_CWD || process.cwd();
    const targetPath = path.join(cwd, AGENTS_FILE);
    const claudeMdPath = path.join(cwd, CLAUDE_FILE);

    console.log(`@kirill.konshin/lint: ${command}`);
    console.log(`Target: ${targetPath}`);

    const { exists, generated, customSection } = checkExisting(targetPath);

    if (command === 'init') {
        if (exists && !generated) {
            console.log(`${AGENTS_FILE} exists and was not generated by this tool. Skipping.`);
            console.log('Use "lint-prepare update" to force overwrite, then merge manually.');
            return;
        }

        if (exists && generated) {
            console.log(`${AGENTS_FILE} exists and was generated by this tool. Updating...`);
        }
    }

    if (command === 'update' || command === 'init') {
        checkClaudeMdSafety(claudeMdPath);

        const rules = readRules();
        console.log(`Found ${rules.length} rule files: ${rules.map((r) => r.name).join(', ')}`);

        const skills = readSkills();
        console.log(`Found ${skills.length} skill(s): ${skills.map((s) => s.name).join(', ')}`);

        const commands = readCommands();
        console.log(`Found ${commands.length} command(s): ${commands.map((c) => c.replace(/\.md$/, '')).join(', ')}`);

        const userFiles = readUserFiles(cwd);
        syncAgentDirs(cwd, packageFiles(rules, skills, commands), userFiles);
        console.log(
            `Synced ${AGENT_DIRS.join(', ')}, mirrored ${userFiles.size} own file(s) from ${CANONICAL_AGENT_DIR}`,
        );

        const content = generateAgentsFile(installedRules(rules, userFiles), customSection);
        fs.writeFileSync(targetPath, content, 'utf-8');
        console.log(`${exists ? 'Updated' : 'Created'} ${AGENTS_FILE}`);

        symlinkClaudeMd(cwd);
        console.log(`Symlinked ${CLAUDE_FILE} -> ${AGENTS_FILE}`);
        return;
    }

    console.log(`Unknown command: ${command}`);
    console.log('Usage: lint-prepare [init|update]');
    process.exit(1);
}

// Only run when executed directly (e.g. `lint-prepare init`), not when imported.
if (process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(__filename)) {
    main();
}
