import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import { builtinModules, createRequire } from 'node:module';
import * as path from 'node:path';
import * as process from 'node:process';
import { checkPackage, createPackageFromTarballData, type Problem, type ResolutionKind } from '@arethetypeswrong/core';
import { problemKindInfo } from '@arethetypeswrong/core/problems';
import { globSync } from 'glob';

export const pkgPath = path.join(process.cwd(), 'package.json');

export const distDir = './dist';

//TODO Re-read in fixExports
// import pkg from './package.json' assert { type: 'json' };
// export { pkg };
export const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

export const rootPkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json'), 'utf-8'));

export const formats = ['es'] as const;

export const entryGlob = 'src/index.ts';
export const excludeGlob = 'src/**/*.{stories,test,fixture}.{ts,tsx}';
export const includeGlob = 'src/**/!(*.stories|*.test,fixture).{ts,tsx}';
export const foldersGlob = 'src/*/';

const packageDependencies = [...Object.keys(pkg.dependencies || {}), ...Object.keys(pkg.devDependencies || {})];

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const packageExternals = (packageName: string) => [packageName, new RegExp(`^${escapeRegExp(packageName)}/`)];

// Keep this static: Rolldown passes strings and regular expressions directly to its native binding,
// while callback-based externalization has behaved differently between macOS and Linux CI.
export const external = [
    /^@kirill\.konshin\//,
    ...packageDependencies.flatMap(packageExternals),
    ...builtinModules.flatMap((moduleName) => [moduleName, `node:${moduleName}`]),
    ...packageExternals('builder-util-runtime'),
    /node_modules/,
];

/*
 * Every subpath needs its own rollup input — being merely reachable from the main barrel is not
 * enough. With `preserveModules` a pure re-export barrel is inlined into its importer, so
 * `dist/<mod>/index.js` is never written while `fixExports()` still points `./<mod>` at it (only
 * modules carrying a `'use client'` directive survived by accident). Derived from the same
 * `foldersGlob` as the exports map so the two can't disagree; the `index.ts` files themselves are
 * (re)generated by `generateIndex()` at buildStart — after this glob, before rollup resolves inputs.
 */
export const entry = [...globSync(entryGlob), ...globSync(foldersGlob).map((dir) => path.join(dir, 'index.ts'))];

/*
 * Flat condition map for one entry, `types` first — conditions are matched in declaration order,
 * so the runtime keys must never shadow it.
 *
 * ESM only, so there is deliberately NO `require` condition — nothing here claims CJS support (the
 * lone legitimate CJS artifact in this repo is `@kirill.konshin/lint`'s `./yarn` entry, which Yarn
 * constraints force). `default` is NOT a CJS build, it is the catch-all branch, and it is what makes
 * the entry RESOLVABLE at all: the old nested `{import: {import, types}}` map matched no condition
 * outside `import`, so anything resolving as CJS got ERR_PACKAGE_PATH_NOT_EXPORTED rather than an
 * interop error — Next.js transpiles `next.config.ts` to CommonJS and `require()`s it, which is
 * exactly how `@kirill.konshin/next/config` became unreachable. Node >= 22.12 then loads the ESM
 * through `require()` (nothing here uses top-level await). `attw`'s node16-cjs/node10 complaints are
 * expected — see `ignoredResolutionKinds`, which mirrors `--profile esm-only`.
 */
// https://johnnyreilly.com/dual-publishing-esm-cjs-modules-with-tsup-and-are-the-types-wrong
// https://www.npmjs.com/package/@arethetypeswrong/cli
// FIXME https://github.com/andrewbranch/example-subpath-exports-ts-compat
const exportConditions = (base: string) => ({
    types: `${base}.d.ts`,
    import: `${base}.js`,
    default: `${base}.js`,
});

export async function fixExports() {
    const modules = globSync(foldersGlob).map((file) => path.basename(file));

    // Exports

    //FIXME Entries, formats, etc.
    const mainExport = exportConditions(`${distDir}/index`);

    pkg.exports = { '.': mainExport };

    for (const entry of modules) {
        pkg.exports[`./${entry}`] = exportConditions(`${distDir}/${entry}/index`);
    }

    // Main

    pkg.type = 'module';
    pkg.main = pkg.module = mainExport.import;
    pkg.types = mainExport.types;

    /*
     * Without `files`, npm pack falls back to .npmignore/.gitignore — and dist/ is gitignored, so
     * published tarballs would contain only the auto-included entrypoint, none of the preserved
     * per-module files the exports map points at (checkTypes catches this as resolution errors).
     */
    pkg.files = ['dist'];

    // Author & License

    // TODO Move to root build + set private=true for demos + set react version
    pkg.publishConfig = { access: 'public' };
    pkg.author = 'Kirill Konshin <kirill@konshin.org> (https://konshin.org)';
    pkg.license = 'MIT';

    // Scripts

    // pkg.scripts.clean = 'rm -rf dist .tscache tsconfig.tsbuildinfo';
    // pkg.scripts.build = 'vite build';
    // pkg.scripts.start = 'yarn build --watch';
    pkg.scripts.wait = `wait-on ${mainExport.import}`; // artifact presence detector, see "wait" target in nx.json

    // Ensure peer deps are correct & meta is set
    // Empty peerDependenciesMeta is inert and yarn strips it on manifest rewrites,
    // so it must only be present when there are peer dependencies

    const peerDependencies = Object.entries(pkg.peerDependencies || {});

    if (peerDependencies.length === 0) {
        delete pkg.peerDependenciesMeta;
    } else {
        pkg.peerDependenciesMeta = {};

        for (const [key, _] of peerDependencies) {
            const root = rootPkg.devDependencies[key]; // lifted to root
            const srcPkg = root ? rootPkg : pkg;

            if (!srcPkg.devDependencies?.[key]) throw new Error(`Key ${key} not found in devDependencies`);

            pkg.peerDependenciesMeta[key] = { optional: true };

            const version = srcPkg.devDependencies[key].split('.');

            pkg.peerDependencies[key] = version[0] === '^0' ? `${version[0]}.${version[1]}` : version[0];
        }
    }

    // Write

    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

    console.log('Updated package.json with exports');
    // console.log(pkg);
    // console.log(pkg.exports);
}

/**
 * ┌───────────────┬─────────────────────────────────────────────┐
 * │    version    │                   result                    │
 * ├───────────────┼─────────────────────────────────────────────┤
 * │ 2.6.4 – 2.7.0 │ correct (one line per file)                 │
 * ├───────────────┼─────────────────────────────────────────────┤
 * │ 2.7.1 – 2.7.3 │ duplicated cache line 3x, but no data loss  │
 * ├───────────────┼─────────────────────────────────────────────┤
 * │ 2.7.4         │ crashes (ENOENT)                            │
 * ├───────────────┼─────────────────────────────────────────────┤
 * │ 2.7.5 – 2.8.1 │ silently drops sibling files (what you hit) │
 * └───────────────┴─────────────────────────────────────────────┘
 *
 * Console output in later versions: ctix.Debugger.it.enable = true
 */
export async function generateIndex() {
    const ctix = createRequire(import.meta.url)('ctix');

    // ctix's `creating(buildOptions, createOption)` ignores its first argument entirely (it's
    // unused dead code in ctix's implementation), so only a single, fully-formed `createOption`
    // matters here - there's nothing to parse/cast via parseConfig().
    const options = {
        mode: 'create' as never,
        project: 'tsconfig.json',
        include: 'src/**/*.{ts,tsx}',
        exclude: ['**/*.stories.*', '**/*.test.*', '**/*.fixture.*'],
        startFrom: 'src',
        exportFilename: 'index.ts', // required: without it ctix joins dirPath + undefined => EISDIR on the bare dir
        quote: "'", // rendered verbatim into generated files, must not be left undefined
        useSemicolon: true,
        backup: false,
        overwrite: true,
        generationStyle: 'default-alias-named-star',
        skipEmptyDir: false,
        verbose: true, // unused by ctix.creating() itself, kept for documentation of intent
    };

    // 2.6.4 has no verbose flag - Spinner/ProgressBar/Reasoner default to disabled and are only
    // enabled by ctix's own CLI wrapper (buildCommand), which we bypass by calling creating() directly.
    ctix.ProgressBar.it.enable = true;
    ctix.Spinner.it.enable = true;
    ctix.Reasoner.it.enable = true;

    try {
        await ctix.creating(undefined, options as any);
    } finally {
        ctix.ProgressBar.it.stop();
        ctix.Spinner.it.stop();
    }
}

/*
 * TS emits relative import specifiers into .d.ts verbatim — extensionless, as written in source —
 * but node16/nodenext ESM resolution requires explicit paths ('./worker.js', './form/index.js').
 * Runtime output is already correct (rollup appends '.js'), so only declarations need the rewrite.
 * The src tree (mirrored 1:1 into dist via preserveModules) decides file vs directory — dist itself
 * may be only partially emitted when this hook runs.
 */
export function fixDtsExtensions(filePath: string, content: string): string {
    if (!/\.d\.[cm]?ts$/.test(filePath)) return content;

    const fileSrcDir = path.dirname(path.join(path.resolve('./src'), path.relative(path.resolve(distDir), filePath)));

    return content.replace(/(\bfrom\s+|\bimport\s*\()(['"])(\.\.?\/[^'"]+)\2/g, (match, prefix, quote, spec) => {
        const target = path.resolve(fileSrcDir, spec);

        if (fs.existsSync(`${target}.ts`) || fs.existsSync(`${target}.tsx`))
            return `${prefix}${quote}${spec}.js${quote}`;
        if (fs.existsSync(path.join(target, 'index.ts'))) return `${prefix}${quote}${spec}/index.js${quote}`;

        return match; // already extensioned, non-source asset, or outside src — leave untouched
    });
}

/*
 * Mirrors `attw --profile esm-only`: these packages deliberately ship ESM only (exports maps carry
 * just an `import` condition), so failures of the require-based resolutions are expected, not defects.
 */
const ignoredResolutionKinds: readonly ResolutionKind[] = ['node10', 'node16-cjs'];

function isIgnoredProblem(problem: Problem): boolean {
    return 'resolutionKind' in problem && ignoredResolutionKinds.includes(problem.resolutionKind);
}

function formatProblem(problem: Problem): string {
    const info = problemKindInfo[problem.kind];
    const entrypoint = 'entrypoint' in problem ? problem.entrypoint : undefined;
    const resolution =
        'resolutionKind' in problem
            ? problem.resolutionKind
            : 'resolutionOption' in problem
              ? problem.resolutionOption
              : undefined;
    const fileName = 'fileName' in problem ? problem.fileName : undefined;
    const moduleSpecifier = 'moduleSpecifier' in problem ? problem.moduleSpecifier : undefined;

    const where = [
        entrypoint !== undefined && `entrypoint "${entrypoint}"`,
        resolution && `resolution ${resolution}`,
        fileName && `file ${fileName}`,
        moduleSpecifier && `import "${moduleSpecifier}"`,
    ]
        .filter(Boolean)
        .join(', ');

    return `${info.emoji} ${info.title} (${where || JSON.stringify(problem)}): ${info.shortDescription}. ${info.docsUrl}`;
}

export async function checkTypes() {
    // https://www.npmjs.com/package/@arethetypeswrong/core
    const { filename } = JSON.parse(execSync('npm pack --json', { encoding: 'utf-8' }))[0];

    try {
        const data = new Uint8Array(fs.readFileSync(filename));
        const analysis = await checkPackage(createPackageFromTarballData(data));

        if (!analysis.types) throw new Error(`@arethetypeswrong found no types in ${pkg.name}`);

        const problems = analysis.problems.filter((problem) => !isIgnoredProblem(problem));

        if (problems.length > 0) {
            for (const problem of problems) console.warn(formatProblem(problem));

            throw new Error(`@arethetypeswrong found ${problems.length} problem(s) in ${pkg.name}`);
        } else {
            console.log('Types check passed');
        }
    } finally {
        fs.rmSync(filename);
    }
}
