name: PR Check

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  pr:
    name: PR Check
    runs-on: ubuntu-latest
    env:
      TURBO_CACHE_DIR: .turbo

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # https://github.com/changesets/changesets/issues/517#issuecomment-1239303017

      - if: ${{ github.event.pull_request.title != 'Version Packages' }}
        run: git pull --force --no-tags origin main:main

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      #TODO https://turbo.build/repo/docs/guides/ci-vendors/github-actions#remote-caching
      #TODO https://turborepo.dev/docs/guides/ci-vendors/github-actions#remote-caching-with-github-actionscache
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      #      - name: Cache Next.js
      #        uses: actions/cache@v4
      #        with:
      #          path: |
      #            packages/.next/cache
      #          key: ${{ runner.os }}-next-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('packages/**/*.[jt]s', 'apps/web/**/*.[jt]sx', 'apps/web/**/*.json') }}
      #          restore-keys: |
      #            ${{ runner.os }}-next-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}-
      #            ${{ runner.os }}-next-main-${{ hashFiles('yarn.lock') }}-
      #            ${{ runner.os }}-next-

      - name: Lint
        run: yarn lint:all

      - name: Test
        run: yarn test

      # https://josh-ops.com/posts/github-code-coverage/
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'packages/*/coverage/cobertura-coverage.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Build
        run: yarn build

      # https://github.com/changesets/action?tab=readme-ov-file#without-publishing
      #- name: Create Release Pull Request
      #  uses: changesets/action@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Check Changesets
      #  if: ${{ github.event.pull_request.title != 'Version Packages' }}
      #  run: yarn changeset status --since=main
